from __future__ import annotations

import argparse
from collections.abc import Mapping
from dataclasses import dataclass
from functools import lru_cache
import json
import math
from pathlib import Path
import re

from shapely import affinity
from shapely.geometry import box

from tools.lh60_design.interconnect import interboard_contract
from tools.lh60_design.interconnect_library import interconnect_footprint_spec
from tools.lh60_design.layout import physical_keys
from tools.lh60_design.mcp import McpClient
from tools.lh60_design.project import BOARD_HEIGHT_MM, BOARD_WIDTH_MM
from tools.lh60_design.socket_geometry import build_footprint_specs
from tools.lh60_design.socket_library import _courtyard_geometry
from tools.lh60_design.schematic import _switch_footprint, switch_references


ROOT = Path(__file__).resolve().parents[2]
BOARD = ROOT / "lh60.kicad_pcb"
REGION_REPORTS = ROOT / "docs" / "regions"
LEGACY_CONNECTOR_BASELINE = (
    ROOT / "docs" / "reports" / "2026-08-18-debug-connectors-baseline.json"
)
PASSIVE_CONNECTOR_REFERENCE = "J1"
PASSIVE_CONNECTOR_FOOTPRINT = "lh60-interconnect:FPC-05F-24PH20"
PASSIVE_CONNECTOR_VALUE = "FPC-05F-24PH20"
PASSIVE_LEGACY_REMOVALS = ("U1", "J2", "J3", "J4", "J5", "J6")
LEGACY_CONNECTOR_REFERENCES = ("J1", "J2", "J3", "J4", "J5", "J6")
CONNECTOR_PIN_COUNTS = {"J1": 3, "J2": 5, "J3": 5, "J4": 4, "J5": 3, "J6": 3}
CANDIDATE_OFFSETS_MM = (
    (0.0, 0.0),
    (-5.0, 0.0),
    (5.0, 0.0),
    (0.0, -5.0),
    (0.0, 5.0),
    (-5.0, -5.0),
    (5.0, -5.0),
    (-5.0, 5.0),
    (5.0, 5.0),
    (-10.0, 0.0),
    (10.0, 0.0),
    (0.0, -10.0),
    (0.0, 10.0),
    (-10.0, -10.0),
    (10.0, -10.0),
    (-10.0, 10.0),
    (10.0, 10.0),
)
CANDIDATE_ROTATIONS_DEG = (0.0, 90.0, 180.0, 270.0)
BOARD_ACCESS_MARGIN_MM = 0.5
FFC_STIFFENER_INSERTION_MM = 6.0
FFC_FIRST_BEND_CLEARANCE_MM = 6.0
PASSIVE_FFC_SEARCH_GRID_MM = 0.5
REVIEWED_PLACEMENT_OVERRIDE_REASON = (
    "The planned 408-candidate legacy-centroid search was exhausted: "
    "all candidates were outside production board access bounds because "
    "the source test points were outside the board outline. "
    "FROZEN_CONNECTOR_PLACEMENTS is a user-reviewed override subsequently "
    "validated by live access, courtyard, and DRC evidence; it was not "
    "generated by that search."
)
REVIEWED_ROTATION_OVERRIDES_DEG = {
    "r0_top_split_left_fn_1u": 0.0,
    "r2_enter_ansi_2.25u": 180.0,
    "r2_enter_split_left_fn_1u": 0.0,
    "r2_enter_split_right_1.25u": 0.0,
    "r3_lshift_split_left_fn_1u": 0.0,
    "r3_lshift_2.25u": 180.0,
    "r3_lshift_split_1.25u": 0.0,
}


@dataclass(frozen=True)
class FootprintPlacement:
    physical_key_id: str
    reference: str
    x_mm: float
    y_mm: float
    rotation_deg: float
    layer: str = "F.Cu"


@dataclass(frozen=True)
class AxisAlignedRect:
    min_x: float
    min_y: float
    max_x: float
    max_y: float

    def distance_to(self, other: "AxisAlignedRect") -> float:
        dx = max(other.min_x - self.max_x, self.min_x - other.max_x, 0.0)
        dy = max(other.min_y - self.max_y, self.min_y - other.max_y, 0.0)
        return math.hypot(dx, dy)

    def corners(self) -> tuple[tuple[float, float], ...]:
        return (
            (self.min_x, self.min_y),
            (self.max_x, self.min_y),
            (self.max_x, self.max_y),
            (self.min_x, self.max_y),
        )


@dataclass(frozen=True)
class ConnectorPlacement:
    reference: str
    pin_count: int
    x_mm: float
    y_mm: float
    rotation_deg: float
    layer: str = "B.Cu"
    extraction_clearance_mm: float = 15.0

    def __post_init__(self) -> None:
        if self.pin_count < 1:
            raise ValueError("connector placement pin_count must be positive")
        if not all(
            math.isfinite(value)
            for value in (self.x_mm, self.y_mm, self.rotation_deg)
        ):
            raise ValueError("connector placement coordinates must be finite")
        if self.rotation_deg not in (0.0, 180.0):
            raise ValueError("connector placement rotation must be 0 or 180 degrees")
        if self.layer != "B.Cu":
            raise ValueError("connector placement layer must be B.Cu")
        if not math.isfinite(self.extraction_clearance_mm) or self.extraction_clearance_mm <= 0:
            raise ValueError("connector extraction clearance must be positive")

    @property
    def pin1_direction(self) -> str:
        if self.rotation_deg == 0.0:
            return "south"
        return "north"

    def access_envelope(self) -> AxisAlignedRect:
        """Return the XY housing envelope plus 1 mm assembly clearance.

        The project-local header is 2.54 mm wide and ``pin_count * 2.54``
        long.  After the canonical front definition is flipped to B.Cu, its
        pins extend toward negative local Y.  Cable extraction is vertical
        (Z); ``extraction_clearance_mm`` records that separate volume.
        """

        half_width = 2.54 / 2.0 + 1.0
        pin1_end = 2.54 / 2.0 + 1.0
        far_end = (self.pin_count - 1) * 2.54 + pin1_end
        if self.rotation_deg == 0.0:
            min_y = self.y_mm - far_end
            max_y = self.y_mm + pin1_end
        else:
            min_y = self.y_mm - pin1_end
            max_y = self.y_mm + far_end
        return AxisAlignedRect(
            min_x=self.x_mm - half_width,
            min_y=min_y,
            max_x=self.x_mm + half_width,
            max_y=max_y,
        )


@dataclass(frozen=True)
class PassiveFfcPlacement:
    reference: str
    x_mm: float
    y_mm: float
    rotation_deg: float
    layer: str = "B.Cu"
    stiffener_insertion_mm: float = FFC_STIFFENER_INSERTION_MM
    first_bend_clearance_mm: float = FFC_FIRST_BEND_CLEARANCE_MM
    copper_to_edge_mm: float = BOARD_ACCESS_MARGIN_MM

    def __post_init__(self) -> None:
        if self.reference != PASSIVE_CONNECTOR_REFERENCE:
            raise ValueError("passive FFC placement reference must be J1")
        if self.layer != "B.Cu":
            raise ValueError("passive FFC placement layer must be B.Cu")
        if self.rotation_deg not in (0.0, 90.0, 180.0, 270.0):
            raise ValueError("passive FFC placement rotation must be a quarter turn")
        if not all(
            math.isfinite(value)
            for value in (
                self.x_mm,
                self.y_mm,
                self.rotation_deg,
                self.stiffener_insertion_mm,
                self.first_bend_clearance_mm,
                self.copper_to_edge_mm,
            )
        ):
            raise ValueError("passive FFC placement values must be finite")
        if self.stiffener_insertion_mm != FFC_STIFFENER_INSERTION_MM:
            raise ValueError("passive FFC stiffener insertion must be exactly 6 mm")
        if self.first_bend_clearance_mm < self.stiffener_insertion_mm:
            raise ValueError("passive FFC first bend must start outside stiffener zone")
        if self.copper_to_edge_mm < BOARD_ACCESS_MARGIN_MM:
            raise ValueError("passive FFC copper-to-edge must be at least 0.50 mm")

    @property
    def mouth_direction(self) -> str:
        x, y = self._transform_local_point(0.0, 1.0)
        dx = x - self.x_mm
        dy = y - self.y_mm
        if abs(dx) > abs(dy):
            return "east" if dx > 0 else "west"
        return "south" if dy > 0 else "north"

    @property
    def mouth_edge(self) -> str:
        return {
            "north": "top",
            "south": "bottom",
            "west": "left",
            "east": "right",
        }[self.mouth_direction]

    def _transform_local_point(self, x: float, y: float) -> tuple[float, float]:
        if self.layer == "B.Cu":
            y = -y
        angle = int(self.rotation_deg) % 360
        if angle == 0:
            tx, ty = x, y
        elif angle == 90:
            tx, ty = -y, x
        elif angle == 180:
            tx, ty = -x, -y
        else:
            tx, ty = y, -x
        return self.x_mm + tx, self.y_mm + ty

    def _rotated_rect(self, rect: AxisAlignedRect) -> AxisAlignedRect:
        transformed = [self._transform_local_point(x, y) for x, y in rect.corners()]
        xs = [point[0] for point in transformed]
        ys = [point[1] for point in transformed]
        return AxisAlignedRect(min(xs), min(ys), max(xs), max(ys))

    def body_envelope(self) -> AxisAlignedRect:
        spec = interconnect_footprint_spec()
        return self._rotated_rect(
            AxisAlignedRect(
                spec.fab_min_x,
                spec.fab_min_y,
                spec.fab_max_x,
                spec.fab_max_y,
            )
        )

    def courtyard_envelope(self) -> AxisAlignedRect:
        return self._rotated_rect(_passive_ffc_courtyard_local_rect())

    def access_envelope(self) -> AxisAlignedRect:
        courtyard = self.courtyard_envelope()
        if self.mouth_direction == "north":
            return AxisAlignedRect(
                courtyard.min_x,
                max(BOARD_ACCESS_MARGIN_MM, courtyard.min_y - self.stiffener_insertion_mm),
                courtyard.max_x,
                courtyard.max_y,
            )
        if self.mouth_direction == "south":
            return AxisAlignedRect(
                courtyard.min_x,
                courtyard.min_y,
                courtyard.max_x,
                min(BOARD_HEIGHT_MM - BOARD_ACCESS_MARGIN_MM, courtyard.max_y + self.stiffener_insertion_mm),
            )
        if self.mouth_direction == "west":
            return AxisAlignedRect(
                max(BOARD_ACCESS_MARGIN_MM, courtyard.min_x - self.stiffener_insertion_mm),
                courtyard.min_y,
                courtyard.max_x,
                courtyard.max_y,
            )
        return AxisAlignedRect(
            courtyard.min_x,
            courtyard.min_y,
            min(BOARD_WIDTH_MM - BOARD_ACCESS_MARGIN_MM, courtyard.max_x + self.stiffener_insertion_mm),
            courtyard.max_y,
        )


@dataclass(frozen=True)
class PassiveFfcCandidateAudit:
    placement: PassiveFfcPlacement
    rejection_reasons: tuple[str, ...]

    @property
    def viable(self) -> bool:
        return not self.rejection_reasons


@dataclass(frozen=True)
class LegacyConnectorCandidate:
    """One pose from the superseded bounded legacy-centroid search."""

    reference: str
    pin_count: int
    x_mm: float
    y_mm: float
    rotation_deg: float

    def __post_init__(self) -> None:
        if self.reference not in LEGACY_CONNECTOR_REFERENCES:
            raise ValueError(f"unexpected legacy connector reference: {self.reference}")
        if self.pin_count != CONNECTOR_PIN_COUNTS[self.reference]:
            raise ValueError(f"unexpected pin count for {self.reference}")
        if not all(
            math.isfinite(value)
            for value in (self.x_mm, self.y_mm, self.rotation_deg)
        ):
            raise ValueError("legacy connector candidate coordinates must be finite")
        if self.rotation_deg not in CANDIDATE_ROTATIONS_DEG:
            raise ValueError("legacy connector candidate rotation must be a quarter turn")

    def access_envelope(self) -> AxisAlignedRect:
        half_width = 2.54 / 2.0 + 1.0
        pin1_end = 2.54 / 2.0 + 1.0
        far_end = (self.pin_count - 1) * 2.54 + pin1_end

        if self.rotation_deg == 0.0:
            local_bounds = (-half_width, -far_end, half_width, pin1_end)
        elif self.rotation_deg == 90.0:
            local_bounds = (-pin1_end, -half_width, far_end, half_width)
        elif self.rotation_deg == 180.0:
            local_bounds = (-half_width, -pin1_end, half_width, far_end)
        else:
            local_bounds = (-far_end, -half_width, pin1_end, half_width)

        min_x, min_y, max_x, max_y = local_bounds
        return AxisAlignedRect(
            min_x=self.x_mm + min_x,
            min_y=self.y_mm + min_y,
            max_x=self.x_mm + max_x,
            max_y=self.y_mm + max_y,
        )


@dataclass(frozen=True)
class LegacyPlacementAudit:
    placement: LegacyConnectorCandidate
    offset_x_mm: float
    offset_y_mm: float
    envelope: AxisAlignedRect
    rejection_reasons: tuple[str, ...]

    @property
    def viable(self) -> bool:
        return not self.rejection_reasons


FROZEN_CONNECTOR_PLACEMENTS = (
    ConnectorPlacement("J1", 3, 282.5, 36.0, 0.0),
    ConnectorPlacement("J2", 5, 77.5, 92.0, 0.0),
    ConnectorPlacement("J3", 5, 107.5, 92.0, 0.0),
    ConnectorPlacement("J4", 4, 3.0, 49.5, 0.0),
    ConnectorPlacement("J5", 3, 3.0, 55.5, 180.0),
    ConnectorPlacement("J6", 3, 282.5, 42.0, 180.0),
)


def _passive_ffc_courtyard_local_rect() -> AxisAlignedRect:
    spec = interconnect_footprint_spec()
    min_x = min(
        [spec.fab_min_x]
        + [pad.x - pad.width / 2 for pad in spec.pads]
    ) - spec.courtyard_clearance_mm
    max_x = max(
        [spec.fab_max_x]
        + [pad.x + pad.width / 2 for pad in spec.pads]
    ) + spec.courtyard_clearance_mm
    min_y = min(
        [spec.fab_min_y]
        + [pad.y - pad.height / 2 for pad in spec.pads]
    ) - spec.courtyard_clearance_mm
    max_y = max(
        [spec.fab_max_y]
        + [pad.y + pad.height / 2 for pad in spec.pads]
    ) + spec.courtyard_clearance_mm
    return AxisAlignedRect(min_x, min_y, max_x, max_y)


def _top_edge_passive_ffc_candidates() -> tuple[PassiveFfcPlacement, ...]:
    y = BOARD_ACCESS_MARGIN_MM + _passive_ffc_courtyard_local_rect().max_y
    top_row = sorted(
        (placement.x_mm for placement in socket_placement_plan() if placement.y_mm < 20.0)
    )
    between_keys = tuple(
        (left + right) / 2
        for left, right in zip(top_row, top_row[1:])
        if right - left > 4.0
    )
    return tuple(PassiveFfcPlacement("J1", x, y, 0.0) for x in between_keys)


def _frange(start: float, stop: float, step: float) -> tuple[float, ...]:
    values = []
    value = math.ceil(start / step) * step
    while value <= stop + 1e-9:
        values.append(round(value, 6))
        value += step
    return tuple(values)


def _candidate_sweep_range(
    sample_courtyard: AxisAlignedRect,
    *,
    axis: str,
) -> tuple[float, ...]:
    if axis == "x":
        start = BOARD_ACCESS_MARGIN_MM - sample_courtyard.min_x
        stop = BOARD_WIDTH_MM - BOARD_ACCESS_MARGIN_MM - sample_courtyard.max_x
    else:
        start = BOARD_ACCESS_MARGIN_MM - sample_courtyard.min_y
        stop = BOARD_HEIGHT_MM - BOARD_ACCESS_MARGIN_MM - sample_courtyard.max_y
    return _frange(start, stop, PASSIVE_FFC_SEARCH_GRID_MM)


def _edge_candidate_fixed_coordinate(
    sample_courtyard: AxisAlignedRect,
    *,
    edge: str,
) -> float:
    if edge == "top":
        return BOARD_ACCESS_MARGIN_MM - sample_courtyard.min_y
    if edge == "bottom":
        return BOARD_HEIGHT_MM - BOARD_ACCESS_MARGIN_MM - sample_courtyard.max_y
    if edge == "left":
        return BOARD_ACCESS_MARGIN_MM - sample_courtyard.min_x
    if edge == "right":
        return BOARD_WIDTH_MM - BOARD_ACCESS_MARGIN_MM - sample_courtyard.max_x
    raise ValueError(f"unsupported edge: {edge}")


def _edge_passive_ffc_candidates() -> tuple[PassiveFfcPlacement, ...]:
    rotations_by_edge = {
        "top": 0.0,
        "bottom": 180.0,
        "left": 270.0,
        "right": 90.0,
    }
    candidates = []
    for edge, rotation in rotations_by_edge.items():
        sample = PassiveFfcPlacement("J1", 0.0, 0.0, rotation).courtyard_envelope()
        if edge in {"top", "bottom"}:
            y = _edge_candidate_fixed_coordinate(sample, edge=edge)
            for x in _candidate_sweep_range(sample, axis="x"):
                candidates.append(PassiveFfcPlacement("J1", x, y, rotation))
        else:
            x = _edge_candidate_fixed_coordinate(sample, edge=edge)
            for y in _candidate_sweep_range(sample, axis="y"):
                candidates.append(PassiveFfcPlacement("J1", x, y, rotation))
    return tuple(candidates)


def _former_mcu_region_passive_ffc_candidates() -> tuple[PassiveFfcPlacement, ...]:
    sample = PassiveFfcPlacement("J1", 0.0, 0.0, 180.0).courtyard_envelope()
    y = _edge_candidate_fixed_coordinate(sample, edge="bottom")
    start = max(60.0, BOARD_ACCESS_MARGIN_MM - sample.min_x)
    stop = min(140.0, BOARD_WIDTH_MM - BOARD_ACCESS_MARGIN_MM - sample.max_x)
    return tuple(
        PassiveFfcPlacement("J1", x, y, 180.0)
        for x in _frange(start, stop, PASSIVE_FFC_SEARCH_GRID_MM)
    )


PASSIVE_FFC_CANDIDATES = (
    PassiveFfcPlacement("J1", 276.0, 7.0, 0.0),
    PassiveFfcPlacement("J1", 276.0, 88.0, 180.0),
    PassiveFfcPlacement("J1", 9.0, 48.0, 270.0),
    PassiveFfcPlacement("J1", 276.0, 48.0, 90.0),
)


def read_legacy_connector_centroids(
    path: Path | str = LEGACY_CONNECTOR_BASELINE,
) -> dict[str, tuple[float, float]]:
    payload = json.loads(Path(path).read_text())
    centroids = payload.get("centroids")
    if not isinstance(centroids, dict):
        raise ValueError("legacy connector baseline is missing centroids")
    if set(centroids) != set(LEGACY_CONNECTOR_REFERENCES):
        raise ValueError("legacy connector centroid references do not match J1..J6")

    result = {}
    for reference in LEGACY_CONNECTOR_REFERENCES:
        centroid = centroids[reference]
        if not isinstance(centroid, dict):
            raise ValueError(f"legacy connector centroid for {reference} is malformed")
        x_mm = centroid.get("x")
        y_mm = centroid.get("y")
        if (
            isinstance(x_mm, bool)
            or isinstance(y_mm, bool)
            or not isinstance(x_mm, (int, float))
            or not isinstance(y_mm, (int, float))
            or not math.isfinite(x_mm)
            or not math.isfinite(y_mm)
        ):
            raise ValueError(f"legacy connector centroid for {reference} is not finite")
        result[reference] = (float(x_mm), float(y_mm))
    return result


def _board_access_rejection_reasons(envelope: AxisAlignedRect) -> tuple[str, ...]:
    min_x = BOARD_ACCESS_MARGIN_MM
    min_y = BOARD_ACCESS_MARGIN_MM
    max_x = BOARD_WIDTH_MM - BOARD_ACCESS_MARGIN_MM
    max_y = BOARD_HEIGHT_MM - BOARD_ACCESS_MARGIN_MM
    reasons = []
    if envelope.min_x < min_x:
        reasons.append("board_min_x")
    if envelope.min_y < min_y:
        reasons.append("board_min_y")
    if envelope.max_x > max_x:
        reasons.append("board_max_x")
    if envelope.max_y > max_y:
        reasons.append("board_max_y")
    return tuple(reasons)


def _geometry_for_rect(rect: AxisAlignedRect):
    return box(rect.min_x, rect.min_y, rect.max_x, rect.max_y)


@lru_cache(maxsize=1)
def _socket_courtyard_geometries() -> tuple[tuple[str, object], ...]:
    specs = {spec.name: spec for spec in build_footprint_specs()}
    geometries = []
    keys_by_id = {key.physical_key_id: key for key in physical_keys()}
    for placement in socket_placement_plan():
        key = keys_by_id[placement.physical_key_id]
        footprint = _switch_footprint(key)
        footprint_name = re.sub(r"^[^:]+:", "", footprint)
        geometry = _courtyard_geometry(specs[footprint_name])
        geometry = affinity.rotate(
            geometry,
            -placement.rotation_deg,
            origin=(0, 0),
        )
        geometry = affinity.translate(
            geometry,
            xoff=placement.x_mm,
            yoff=placement.y_mm,
        )
        geometries.append((placement.reference, geometry))
    return tuple(geometries)


def audit_legacy_connector_search(
    centroids: Mapping[str, tuple[float, float]],
) -> tuple[LegacyPlacementAudit, ...]:
    """Replay the planned search through its first pure board-bound gate."""

    if set(centroids) != set(LEGACY_CONNECTOR_REFERENCES):
        raise ValueError("legacy connector centroid references do not match J1..J6")

    results = []
    for reference in LEGACY_CONNECTOR_REFERENCES:
        centroid_x, centroid_y = centroids[reference]
        if not all(
            isinstance(value, (int, float))
            and not isinstance(value, bool)
            and math.isfinite(value)
            for value in (centroid_x, centroid_y)
        ):
            raise ValueError(f"legacy connector centroid for {reference} is not finite")
        for offset_x, offset_y in CANDIDATE_OFFSETS_MM:
            for rotation in CANDIDATE_ROTATIONS_DEG:
                placement = LegacyConnectorCandidate(
                    reference=reference,
                    pin_count=CONNECTOR_PIN_COUNTS[reference],
                    x_mm=float(centroid_x + offset_x),
                    y_mm=float(centroid_y + offset_y),
                    rotation_deg=rotation,
                )
                envelope = placement.access_envelope()
                results.append(
                    LegacyPlacementAudit(
                        placement=placement,
                        offset_x_mm=offset_x,
                        offset_y_mm=offset_y,
                        envelope=envelope,
                        rejection_reasons=_board_access_rejection_reasons(envelope),
                    )
                )
    return tuple(results)


def frozen_connector_placements() -> tuple[ConnectorPlacement, ...]:
    return FROZEN_CONNECTOR_PLACEMENTS


def passive_board_references() -> frozenset[str]:
    return frozenset(
        {f"D{index}" for index in range(1, 71)}
        | {f"SW{index}" for index in range(1, 59)}
        | {f"SW{index}" for index in range(60, 77)}
        | {PASSIVE_CONNECTOR_REFERENCE}
    )


def passive_connector_pad_nets() -> dict[str, str]:
    return {
        str(pin.number): pin.net_name
        for pin in interboard_contract().pins
        if pin.net_name is not None
    }


def _default_passive_ffc_candidates() -> tuple[PassiveFfcPlacement, ...]:
    candidates = [
        PASSIVE_FFC_CANDIDATES[0],
        *_top_edge_passive_ffc_candidates(),
        *PASSIVE_FFC_CANDIDATES[1:],
        *_edge_passive_ffc_candidates(),
        *_former_mcu_region_passive_ffc_candidates(),
    ]
    deduplicated = []
    seen = set()
    for candidate in candidates:
        key = (
            candidate.reference,
            round(candidate.x_mm, 6),
            round(candidate.y_mm, 6),
            round(candidate.rotation_deg, 6),
            candidate.layer,
        )
        if key in seen:
            continue
        seen.add(key)
        deduplicated.append(candidate)
    return tuple(deduplicated)


def audit_passive_ffc_candidates(
    candidates: tuple[PassiveFfcPlacement, ...] | None = None,
) -> tuple[PassiveFfcCandidateAudit, ...]:
    candidates = _default_passive_ffc_candidates() if candidates is None else candidates
    audits = []
    socket_courtyards = _socket_courtyard_geometries()
    for candidate in candidates:
        reasons = []
        candidate_courtyard = candidate.courtyard_envelope()
        candidate_courtyard_geometry = _geometry_for_rect(candidate_courtyard)
        candidate_access_geometry = _geometry_for_rect(candidate.access_envelope())
        if candidate.courtyard_envelope().distance_to(candidate.access_envelope()) > 0:
            reasons.append("access_envelope_detached")
        for label, envelope in (
            ("body", candidate.body_envelope()),
            ("courtyard", candidate_courtyard),
            ("access", candidate.access_envelope()),
        ):
            reasons.extend(f"{label}_{reason}" for reason in _board_access_rejection_reasons(envelope))
        for reference, socket_courtyard in socket_courtyards:
            if candidate_courtyard_geometry.intersects(socket_courtyard):
                reasons.append(f"courtyard_collision_{reference}")
            if candidate_access_geometry.intersects(socket_courtyard):
                reasons.append(f"access_collision_{reference}")
        if candidate.copper_to_edge_mm < BOARD_ACCESS_MARGIN_MM:
            reasons.append("copper_to_edge")
        if candidate.first_bend_clearance_mm < candidate.stiffener_insertion_mm:
            reasons.append("first_bend_inside_stiffener")
        audits.append(PassiveFfcCandidateAudit(candidate, tuple(reasons)))
    return tuple(audits)


def selected_passive_ffc_candidate() -> PassiveFfcPlacement:
    for audit in audit_passive_ffc_candidates():
        if audit.viable:
            return audit.placement
    raise RuntimeError("no passive FFC placement candidate passed the bounded search")


def apply_passive_ffc_placement(
    client: McpClient,
    board: Path | str = BOARD,
) -> tuple[dict[str, object], ...]:
    board_path = str(board)
    schemas = client.tool_schemas("pcb_components")
    if "flip_component" not in schemas:
        raise RuntimeError("Konnect pcb_components is missing required tool: flip_component")
    if "set_component_placements" not in schemas:
        raise RuntimeError("Konnect pcb_components is missing required tool: set_component_placements")

    placement = selected_passive_ffc_candidate()
    flip_result = client.call_tool_json(
        "flip_component",
        {
            "board": board_path,
            "reference": placement.reference,
            "layer": placement.layer,
        },
    )
    if flip_result.get("reference") not in {None, placement.reference}:
        raise RuntimeError("passive FFC flip reference mismatch")
    if flip_result.get("layer") not in {None, placement.layer}:
        raise RuntimeError("passive FFC flip layer mismatch")
    requested = [
        {
            "reference": placement.reference,
            "x": placement.x_mm,
            "y": placement.y_mm,
            "rotation": placement.rotation_deg,
        }
    ]
    result = client.call_tool_json(
        "set_component_placements",
        {"board": board_path, "placements": requested},
    )
    placements = result.get("placements")
    if not isinstance(placements, list) or len(placements) != 1:
        raise RuntimeError("passive FFC placement evidence must contain one item")
    item = placements[0]
    if not isinstance(item, dict) or item.get("reference") != "J1":
        raise RuntimeError("passive FFC placement reference mismatch")
    for field, expected in requested[0].items():
        if field == "reference":
            continue
        if not _matches_finite_numeric_evidence(item.get(field), expected):
            raise RuntimeError(f"passive FFC placement {field} mismatch")
    return ({**requested[0], "layer": placement.layer, "flip": flip_result},)


def _balanced_block(source: str, start: int) -> tuple[int, int]:
    depth = 0
    in_string = False
    escaped = False
    for index in range(start, len(source)):
        character = source[index]
        if escaped:
            escaped = False
        elif in_string:
            if character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
        elif character == '"':
            in_string = True
        elif character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
            if depth == 0:
                return start, index + 1
    raise ValueError(f"unbalanced S-expression starting at byte {start}")


def _direct_footprint_blocks(source: str) -> tuple[str, ...]:
    blocks = []
    depth = 0
    in_string = False
    escaped = False
    index = 0
    while index < len(source):
        character = source[index]
        if escaped:
            escaped = False
        elif in_string:
            if character == "\\":
                escaped = True
            elif character == '"':
                in_string = False
        elif character == '"':
            in_string = True
        elif character == "(":
            if depth == 1 and source.startswith("(footprint", index):
                start, end = _balanced_block(source, index)
                blocks.append(source[start:end])
                index = end
                continue
            depth += 1
        elif character == ")":
            depth -= 1
        index += 1
    return tuple(blocks)


def _root_tag_block(source: str, tag: str) -> str:
    marker = f"({tag}"
    for start in range(len(source)):
        if not source.startswith(marker, start):
            continue
        prefix = source[start + len(marker) : start + len(marker) + 1]
        if prefix not in {" ", "\t", "\r", "\n", ")"}:
            continue
        depth = 0
        in_string = False
        escaped = False
        for index, character in enumerate(source[:start]):
            if escaped:
                escaped = False
            elif in_string:
                if character == "\\":
                    escaped = True
                elif character == '"':
                    in_string = False
            elif character == '"':
                in_string = True
            elif character == "(":
                depth += 1
            elif character == ")":
                depth -= 1
        if depth == 1:
            block_start, block_end = _balanced_block(source, start)
            return source[block_start:block_end]
    raise ValueError(f"missing root ({tag} ...) block")


def read_board_placements(
    board: Path | str = BOARD,
) -> dict[str, tuple[float, float, float, str]]:
    source = Path(board).read_text()
    placements = {}
    for block in _direct_footprint_blocks(source):
        reference_marker = '(property "Reference" "'
        reference_start = block.find(reference_marker)
        if reference_start < 0:
            continue
        reference_start += len(reference_marker)
        reference_end = block.find('"', reference_start)
        reference = block[reference_start:reference_end]
        at_tokens = _root_tag_block(block, "at")[1:-1].split()
        layer_block = _root_tag_block(block, "layer")
        layer = layer_block.split('"', 2)[1]
        placements[reference] = (
            float(at_tokens[1]),
            float(at_tokens[2]),
            float(at_tokens[3]) if len(at_tokens) > 3 else 0.0,
            layer,
        )
    return placements


def _region_rotations() -> dict[str, float]:
    rotations: dict[str, float] = {}
    for report_path in sorted(REGION_REPORTS.glob("*.json")):
        report = json.loads(report_path.read_text())
        for placement in report["placements"]:
            physical_key_id = placement["socket_ref"]
            if physical_key_id in rotations:
                raise ValueError(
                    f"duplicate regional placement for {physical_key_id}"
                )
            rotations[physical_key_id] = float(placement["rotation_deg"])
    return rotations


def socket_placement_plan() -> tuple[FootprintPlacement, ...]:
    references = switch_references()
    rotations = _region_rotations()
    rotations.update(REVIEWED_ROTATION_OVERRIDES_DEG)
    keys = physical_keys()
    regional_key_ids = {
        key.physical_key_id for key in keys if key.region is not None
    }
    if set(rotations) != regional_key_ids:
        missing = sorted(regional_key_ids - set(rotations))
        extra = sorted(set(rotations) - regional_key_ids)
        raise ValueError(
            f"regional placement reports do not match layout: missing={missing}, extra={extra}"
        )

    return tuple(
        FootprintPlacement(
            physical_key_id=key.physical_key_id,
            reference=references[key.physical_key_id],
            x_mm=key.center_x_mm,
            y_mm=key.center_y_mm,
            rotation_deg=rotations.get(key.physical_key_id, 0.0),
        )
        for key in keys
    )


def apply_socket_placements(client: McpClient, board: Path | str = BOARD) -> None:
    board_path = str(board)
    schemas = client.tool_schemas("pcb_components")
    missing = {"move_component", "rotate_component"} - set(schemas)
    if missing:
        raise RuntimeError(
            f"Konnect pcb_components is missing required tools: {sorted(missing)}"
        )
    for placement in socket_placement_plan():
        client.call_tool(
            "move_component",
            {
                "board": board_path,
                "reference": placement.reference,
                "x": placement.x_mm,
                "y": placement.y_mm,
            },
        )
        client.call_tool(
            "rotate_component",
            {
                "board": board_path,
                "reference": placement.reference,
                "rotation": placement.rotation_deg,
            },
        )


_BATCH_SET_COMPONENT_POSES_SCHEMA = {
    "additionalProperties": False,
    "properties": {
        "board": {"type": "string"},
        "placements": {
            "items": {
                "additionalProperties": False,
                "properties": {
                    "layer": {
                        "enum": ["F.Cu", "B.Cu"],
                        "type": "string",
                    },
                    "reference": {"type": "string"},
                    "rotation": {"type": "number"},
                    "x": {"type": "number"},
                    "y": {"type": "number"},
                },
                "required": ["reference", "x", "y", "rotation", "layer"],
                "type": "object",
            },
            "type": "array",
        },
    },
    "required": ["board", "placements"],
    "type": "object",
}


def _matches_finite_numeric_evidence(value: object, expected: float) -> bool:
    return (
        type(value) in (int, float)
        and math.isfinite(value)
        and value == expected
    )


def apply_connector_placements(
    client: McpClient,
    board: Path | str = BOARD,
) -> tuple[dict[str, object], ...]:
    board_path = str(board)
    schemas = client.tool_schemas("pcb_components")
    schema = schemas.get("batch_set_component_poses")
    if schema is None:
        raise RuntimeError(
            "Konnect pcb_components is missing required tool: "
            "batch_set_component_poses"
        )
    if schema != _BATCH_SET_COMPONENT_POSES_SCHEMA:
        raise RuntimeError("batch_set_component_poses schema mismatch")

    plan = frozen_connector_placements()
    requested = [
        {
            "reference": placement.reference,
            "x": placement.x_mm,
            "y": placement.y_mm,
            "rotation": placement.rotation_deg,
            "layer": placement.layer,
        }
        for placement in plan
    ]
    result = client.call_tool_json(
        "batch_set_component_poses",
        {"board": board_path, "placements": requested},
    )

    changed = result.get("changed")
    updated_count = result.get("updated_count")
    placements = result.get("placements")
    if result.get("source") != "file":
        raise RuntimeError("atomic connector placement must use the file source")
    if result.get("atomic") is not True:
        raise RuntimeError("atomic connector placement did not prove atomic=true")
    if not isinstance(changed, bool):
        raise RuntimeError("atomic connector placement changed must be bool")
    if isinstance(updated_count, bool) or not isinstance(updated_count, int):
        raise RuntimeError("atomic connector placement updated_count must be int")
    if not isinstance(placements, list) or len(placements) != len(plan):
        raise RuntimeError("atomic connector placement evidence must contain six items")

    evidence = []
    references = []
    changed_count = 0
    for expected, item in zip(requested, placements):
        if not isinstance(item, dict):
            raise RuntimeError("atomic connector placement item must be an object")
        item_changed = item.get("changed")
        if not isinstance(item_changed, bool):
            raise RuntimeError("atomic connector placement item changed must be bool")
        references.append(item.get("reference"))
        if (
            item.get("reference") != expected["reference"]
            or item.get("layer") != expected["layer"]
            or any(
                not _matches_finite_numeric_evidence(
                    item.get(field),
                    expected[field],
                )
                for field in ("x", "y", "rotation")
            )
        ):
            raise RuntimeError("atomic connector placement pose evidence mismatch")
        changed_count += int(item_changed)
        evidence.append({**expected, "changed": item_changed})

    expected_references = [placement.reference for placement in plan]
    if len(set(references)) != len(references) or references != expected_references:
        raise RuntimeError("atomic connector placement references mismatch")
    if updated_count != changed_count:
        raise RuntimeError("atomic connector placement updated_count mismatch")
    if changed is not (updated_count > 0):
        raise RuntimeError("atomic connector placement changed/count mismatch")
    return tuple(evidence)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Place all LH60 production sockets through Konnect."
    )
    parser.add_argument("--board", type=Path, default=BOARD)
    parser.add_argument(
        "--konnect",
        type=Path,
        default=Path.home() / ".local/bin/konnect",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path.home() / ".config/konnect/config.toml",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    with McpClient(args.konnect, args.config) as client:
        apply_socket_placements(client, args.board)


if __name__ == "__main__":
    main()
